title: Aristotelian Observations by a Disappointed yet Effervescent Idealist
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.07101299706846476
  brandStrength: 0.2625681282952428
  rhythmicContrast: 0.6172896202187985
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.8962436451110989
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-71403182-1
  facebook: null
favicon: null
name: Alexander Patouchas
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1164875
layout_spectrum: 0.797491
