name: Alexander Patouchas
favicon: null
layout_spectrum: 0.940653866622597
typography_spectrum: 0.6248060625512153
title: Aristotelian Observations by a Disappointed yet Effervescent Idealist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71403182-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2625681282952428
  lightness: 0.8962436451110989
  saturation: 0.07101299706846476
  rhythmicContrast: 0.6172896202187985
purpose: []
