name: Alexander Patouchas
favicon: null
layout_spectrum: 0.797491
typography_spectrum: 0.06392
title: Aristotelian Observations by a Disappointed yet Effervescent Idealist
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71403182-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2625681282952428
  lightness: 0.8962436451110989
  saturation: 0.07101299706846476
  rhythmicContrast: 0.6172896202187985
purpose: []
